### ISSUE TITLE
How do you even?

### ISSUE THREAD

**Issue by Kenner-G** [ROFaxiuDev/OSBR_Open-sourced-Battle-Royale#1]
How do you even play... like bro, we need documentation.

**Comment by ROFaxiuDev** [comment]
Hey, so this is still in development and i'm currently reworking the whole core. I didnt commit the changes yet, i want to do it when it's smooth and finished. For the documentation i will commit and push it along with the currently in development core-game.

Greeting, MIUPC

**Comment by elisaado** [comment]
I recommend importing this repo in Unity and rebuilding it
